config/routes.rb
LearnyApp::Application.routes.draw do

  get 'workshops/all', as: 'all_workshops'

  namespace :admin do
    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
  
    resources :zones
    resources :reservations, only: [:edit, :destroy, :update, :show]
    resources :venues, :concerns => :paginatable do
      resources :reservations, :concerns => :paginatable, only: [:index, :show]
      resources :calendars, :concerns => :paginatable      
    end
    resources :workshops, :concerns => :paginatable do
       collection do
         get 'proposed(/page/:page)', :action => :proposed, :as => :proposed
         get 'scheduled(/page/:page)', :action => :scheduled, :as => :scheduled
         get 'scheduled/past(/page/:page)', :action => :scheduled_past, :as => :scheduled_past
         get 'given(/page/:page)', :action => :given, :as => :given
       end
       
       member do
         patch 'state'
       end
       
       resources :reservations, only: [:new, :create]
    end

    get '/' => 'administrators#index'
  
  end

  resources :contacts

  devise_for :students, :controllers => { :registrations => "students/registrations" }
  devise_for :experts, :controllers => { :registrations => "experts/registrations" }
  devise_for :venues, :controllers => { :registrations => "venues/registrations" }  
  devise_for :administrators

  get "/auth/:provider/callback" => "sessions#create"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  concern :replicable do
    get '(:id)', :action => :new, :on=> :new, :as => ''
  end

  resources :experts, only: [:show]
  resources :students, only: [:index, :show]
  resources :venues
  resources :venue_pictures
  resources :calendars
  resources :reservations
  resources :workshops, :concerns => [:paginatable, :replicable] do
    resources :student_surveys, only: [:new, :create]
  end
  resources :student_surveys, only: [:show]
  resources :enrollments, :concerns => :paginatable
  resources :guests, only: [:create]
  
  
  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/faq'      => 'high_voltage/pages#show', id: 'faq'

  get '/home', to: redirect('/')
  get 'students/index'
  get 'experts/index'
  get 'venues/index'
  
  authenticated :venue do
    root to: 'venues#index', as: :venue_root
  end

  authenticated :expert do
    root to: 'experts#index', as: :expert_root
  end

  authenticated :student do
    root to: 'students#index', as: :student_root
  end
  
  authenticated :administrator do
    root to: 'admin/administrators#index', as: :administrator_root
  end
  
  unauthenticated do
    root :to => 'high_voltage/pages#show', id: 'home'
  end

end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  
  acts_as_paranoid
  obfuscate_id :spin => 19889937

  include PgSearch
    
  validates :name,:length,:agenda,:description,:state,:expert,:max_number_participants,:min_number_participants, #:zone,
     presence: true
  
  validates :max_number_participants,:min_number_participants, :length, numericality: { only_integer: true, greater_than: 0  }
  
  validates :price, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true, if: :free?
  validates :price, presence: true, numericality: { greater_than: 0 }, unless: :free?
  
  validate :valid_max_participants, :valid_min_participants,:length_fits_with_reservation
    
  attr_accessor :last_event
  
  before_validation
  
  after_validation :set_nil_to_price
  
  state_machine :state, :initial => :new do
    
    state :proposed
    
    state :scheduled
    
    state :stand_by
    
    state :given
    
    state :cancelled
    
    event :proposed_by_expert do
      transition :new => :proposed
    end
    
    event :proposed_with_reservation do
      transition [:new,:proposed] => :scheduled
    end
    
    event :accepted_by_venue do
      transition :proposed => :scheduled
    end
    
    event :cancelled_by_expert do
      transition :scheduled => :cancelled
    end
    
    event :has_been_given do
      transition :scheduled => :given
    end
    
    after_transition :to => any do |workshop, transition|
      #puts ">>>>>>>>>>>>>>>>>> #{transition}"
      workshop.last_event=transition.event  
    end 
    
  end
  
  
  pg_search_scope :search_workshop, 
                  :against => [:name, :description, :agenda],
                  :using => {
                    :tsearch => {:prefix => true}
                  }
  
  
  belongs_to :expert
  has_one :reservation
  belongs_to :zone
  has_one :calendar, through: :reservation 
  has_one :venue, through: :calendar
  
  has_many :enrollments
  has_many :student_surveys
  has_many :students, through: :enrollments
  
  
  accepts_nested_attributes_for :reservation


  scope :proposed, -> {where(state: 'proposed')}
  scope :scheduled, -> {where(state: 'scheduled')}
  scope :given, -> {where(state: 'given')}
  
  scope :next_scheduled, -> {scheduled.joins(:reservation).where('final_time >= ?', Time.now)}
  scope :past_scheduled, -> {scheduled.joins(:reservation).where("final_time < ?", Time.now)}
  
  def free=(free)
    super free
    write_attribute(:price, nil) if free?
  end
  
  def small_description(total_words=250)
    description.truncate(total_words, separator: " ")
  end
  
  def student_enrolled?(student)
    count=enrollments.where(student: student).count
    count > 0
  end
  
  def student_survey_done?(student)
    student_surveys.where(student: student).count > 0
  end
  
  def update_reservation(reservation_id)    
    unless reservation_changes(reservation_id)
      return
    end
    
    
    Workshop.transaction do
      #puts "previous changed? #{reservation.changed?}"
      unless self.reservation.nil?
        reservation=self.reservation
        reservation.workshop_id=nil
        reservation.save
      end
      
      @reservation=Reservation.find(reservation_id) unless reservation_id.nil?||reservation_id.empty?||Reservation.deobfuscate_id(reservation_id).to_i == 0
      #puts "#{@reservation.id}"
      unless @reservation.nil?
        @reservation.workshop = self
        self.proposed_with_reservation
        @reservation.save
        #self.update(:state => :scheduled)
      end
    end
  end

  def proposed_final_time
    if self.proposed_date
      self.proposed_date += self.length.hours
    end
  end
  
  def replicate
    atts=self.attributes.except('id', 'proposed_date', 'zone_id','state')
    Workshop.new(atts)
  end
  
  def self.replicate(id)
    workshop=Workshop.find(id)
    workshop.replicate
  end

  private
  def reservation_changes(reservation_id)
    current_reservation_id = self.reservation.nil? ? nil : reservation.id
    current_reservation_id.to_s != reservation_id.to_s
  end
  
  def valid_max_participants
    if(reservation.present? && (max_number_participants > reservation.max_participants)) 
        message=I18n.t('activerecord.errors.models.reservation.attributes.workshop.too_many_participants', 
          participants: max_number_participants)
        #puts message
        errors.add(:max_number_participants, message)
    end
  end
  
  def length_fits_with_reservation
    if(reservation.present? && (length > reservation.availability_in_hours))
        message=I18n.t('activerecord.errors.models.reservation.attributes.workshop.too_much_time')
        #puts message 
        errors.add(:lenght, message)
    end
  end
  
  def valid_min_participants 
    if( min_number_participants.present? && max_number_participants.present? && 
        min_number_participants > max_number_participants)
        message=I18n.t('activerecord.errors.models.workshop.attributes.min_number_participants.greater_than_max')
        #puts message 
        errors.add(:min_number_participants, message)
    end
  end
  
  def set_nil_to_price
    write_attribute(:price, nil) if (free? && self.errors.empty?)
  end
  
end 

app/controllers/admin/workshops_controller.rb
class Admin::WorkshopsController < Admin::AdminController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy, :state]

  def state
    puts "Workshop: #{@workshop.state} - #{@workshop.state_events} - #{@workshop.state_transitions}"
    changed=@workshop.has_been_given
    
    respond_to do |format|
        if changed
          format.html { redirect_to [:admin, @workshop], notice: "Workshop's state was successfully updated." }
          format.json { head :no_content }
        else
          format.html { redirect_to [:admin, @workshop], alert: "Workshop's state was not updated." }
          format.json { render json: @workshop.errors, status: :unprocessable_entity }
        end
    end
  end


  # GET /admin/workshops
  # GET /admin/workshops.json
  def index
    @workshops = Workshop.all.order('proposed_date desc nulls last').page params[:page]
  end
  
  
  def proposed
    @workshops = Workshop.proposed.order('proposed_date desc nulls last').page params[:page]
  end

  def scheduled
    @workshops = Workshop.scheduled.next_scheduled.order('starts_at').page params[:page]
  end
  
  def scheduled_past
    @workshops = Workshop.scheduled.past_scheduled.order('starts_at desc').page params[:page]
  end
  
  def scheduled
    @workshops = Workshop.scheduled.order('proposed_date desc nulls last').page params[:page]
  end
  
  def given
    @workshops = Workshop.given.order('proposed_date desc nulls last').page params[:page]
  end


  # GET /admin/workshops/1
  # GET /admin/workshops/1.json
  def show
  end

  # GET /admin/workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /admin/workshops/1/edit
  def edit
  end

  # POST /admin/workshops
  # POST /admin/workshops.json
  def create
    @workshop = Workshop.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to [:admin, @workshop], notice: 'Workshop was successfully created.' }
        format.json { render action: 'show', status: :created, location: @workshop }
      else
        format.html { render action: 'new' }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/workshops/1
  # PATCH/PUT /admin/workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to [:admin, @workshop], notice: 'Workshop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/workshops/1
  # DELETE /admin/workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to admin_workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:name, :free, :state, :proposed_date, :zone_id)
    end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_expert!, only: [:create, :update, :destroy]
  
  # GET /workshops
  # GET /workshops.json
  def index
    w=params[:w]
    if !w.nil?
      @guest = Guest.new
      @workshop_solicited = w
      w = Workshop.select(:name).limit(1).order("random()").first.name if w.strip.empty?      
      workshops_scheduled = Workshop.search_workshop(w).joins(:reservation).where("starts_at >= ?", DateTime.now)
      workshops_proposed = Workshop.search_workshop(w).where("state = ? ",'proposed')
      @workshops = workshops_scheduled + workshops_proposed
      @old_workshops = Workshop.search_workshop(w).joins(:reservation).where("starts_at < ?", DateTime.now)
      Search.save_search(current_student, current_expert, current_venue, w)
      render 'search'  
    elsif expert_signed_in? 
      @workshops = current_expert.workshops.page params[:page]
    elsif student_signed_in?
      
    else
      
    end 
       
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    @enrollment = Enrollment.where(:student => current_student, :workshop => @workshop).first 
    @enrollment = Enrollment.new(:student => current_student, :workshop => @workshop) if @enrollment.nil?
  end

  # GET /workshops/new
  def new
    id=params[:id]
    @workshop = id ? Workshop.replicate(id) : Workshop.new
    @workshop.reservation=Reservation.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    Workshop.transaction do
      @workshop = Workshop.create(workshop_params.except(:reservation_attributes)
        .merge({:expert => current_expert}))
      @workshop.proposed_by_expert
      unless workshop_params[:reservation_attributes].nil?
        reservation_id=workshop_params[:reservation_attributes][:id] 
        @workshop.update_reservation(reservation_id) if @workshop.persisted? && reservation_id
        #puts @workshop.errors.full_messages unless @workshop.valid?
        raise ActiveRecord::Rollback if @workshop.invalid?
      end        
    end
    respond_to do |format|
        if @workshop.persisted?
          #TODO Enviar notifiacion a establecimiento de que un curso ha sido calendarizado
          format.html { redirect_to root_path, notice: I18n.t('views.legends.workshop.proposed_successfully',default: 'Workshop successfully proposed.') }
          format.json { render :show, status: :created, location: @workshop }
        else
          format.html { render :new}
          format.json { render json: @workshop.errors, status: :unprocessable_entity }
        end
     end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      updated=false
      Workshop.transaction do       
        unless workshop_params[:reservation_attributes].nil?
          reservation_id=workshop_params[:reservation_attributes][:id] 
          @workshop.update_reservation(reservation_id) if reservation_id
        end
        #puts @workshop.errors.full_messages if @workshop.invalid?
        raise ActiveRecord::Rollback if @workshop.invalid?
        updated=@workshop.update(workshop_params.except(:reservation_attributes))   
      end
      
      if updated
          format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
          format.json { render :show, status: :ok, location: @workshop }
        else
          format.html { render :edit }
          format.json { render json: @workshop.errors, status: :unprocessable_entity }
        end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def all
    @workshops = Workshop.page(params[:page]).per(10)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_workshop
    @workshop = Workshop.find(params[:id])
    @reservation = @workshop.reservation.nil? ? Reservation.new : @workshop.reservation
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def workshop_params
    params.require(:workshop).permit(:name, :target_public, :agenda, :previous_skills, :price, 
      :length, :max_number_participants, :min_number_participants, :description, :free, :proposed_date, :zone_id, reservation_attributes: [:id])
  end
  
  
  
  
end

app/helpers/admin/workshops_helper.rb
module Admin::WorkshopsHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper

	require 'rubygems'
	require 'base64'
	require 'cgi'
	require 'openssl'
	require "json"

	def random_workshop
	  
	  #puts ">>>> #{Workshop.count}"
	  
	  workshop=Workshop.select(:name).limit(1).order("random()").first
		workshop.nil? ? '' : workshop.name		
	end

	def small_description_profile(description,total_words=300)
    	truncate(description,length: total_words,separator: ' ')
  	end
 
	def get_disqus_sso(user)
    # create a JSON packet of our data attributes
    if !user.avatar_url.nil?
	    data = 	{	    	
	      'id' => user.id,
	      'username' => user.full_name,
	      'email' => user.email,
	      'avatar' => user.avatar.icon.url
	    }.to_json
	   else
	   	data = 	{	    	
	      'id' => user.id,
	      'username' => user.full_name,
	      'email' => user.email
	    }.to_json
	   end
 
    # encode the data to base64
    message  = Base64.encode64(data).gsub("\n", "")
    # generate a timestamp for signing the message
    timestamp = Time.now.to_i
    # generate our hmac signature
    sig = OpenSSL::HMAC.hexdigest('sha1', DISQUS_SECRET_KEY, '%s %s' % [message, timestamp])
 
    # return a script tag to insert the sso message
    return "<script type=\"text/javascript\">
        var disqus_config = function() {
            this.page.remote_auth_s3 = \"#{message} #{sig} #{timestamp}\";
            this.page.api_key = \"#{DISQUS_PUBLIC_KEY}\";
        }</script>"
	end
end

app/views/admin/workshops/_form.html.haml
= form_for([:admin, @workshop], html: { class: 'form-horizontal  workshop'} ) do |f|
  - if @workshop.errors.any?
    #error_explanation.panel.panel-danger
      .panel-heading
        %h2.panel-title= "#{pluralize(@workshop.errors.count, "error")} prohibited this workshop from being saved:"
      .panel-body
        %ul
          - @workshop.errors.full_messages.each do |msg|
            %li= msg

  .form-group
    = f.label :name, class: 'control-label col-md-2'
    .col-md-10= f.text_field :name, class: 'form-control'
    .col-md-offset-2.col-md-10
      = f.label :free, for: nil do
        = f.check_box :free
        = Workshop.human_attribute_name(:free)
  .form-group
    = f.label :state, class: 'control-label col-md-2'
    .col-md-10 
      = @workshop.state
  .form-group
    = f.label :proposed_date, class: 'control-label col-md-2'
    .col-md-10= f.datetime_select :proposed_date, class: 'form-control'
  .form-group
    = f.label :zone, class: 'control-label col-md-2'
    .col-md-10= collection_select :workshop, :zone_id, Zone.all, :id, :name, {}, {:class=>'form-control'}
  
    
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, class: 'btn btn-primary'
      

app/views/admin/workshops/_workshops_heading.html.haml
%ul.nav.nav-pills
  %li{:class => "#{'active' if current_page?(admin_workshops_path)}"}
    = link_to  admin_workshops_path do
      = Workshop.model_name.human.pluralize
      %span.badge 
        = Workshop.count
  %li{:class => "#{'active' if current_page?(proposed_admin_workshops_path)}"}
    = link_to proposed_admin_workshops_path do
      = t("views.states.proposed", count: 2, default: 'Proposed')
      %span.badge 
        = Workshop.proposed.count
        
  %li.dropdown
    %a{class: 'dropdown-toggle', 'data-toggle' => 'dropdown', href: '#'}
      = t("views.states.scheduled", count: 2, default: 'Scheduled')
      %span.badge 
        = Workshop.scheduled.count
      %span.caret
    %ul.dropdown-menu
      %li
        = link_to scheduled_admin_workshops_path do
          Siguientes
          %span.badge 
            = Workshop.next_scheduled.count
      %li
        = link_to scheduled_past_admin_workshops_path do
          Anteriores
          %span.badge 
            = Workshop.past_scheduled.count
      
  %li{:class => "#{'active' if current_page?(given_admin_workshops_path)}"}
    = link_to given_admin_workshops_path do
      = t("views.states.given", count: 2, default: 'Given')
      %span.badge 
        = Workshop.given.count

app/views/admin/workshops/edit.html.haml
.page-header
  %h1 Editing workshop

= render 'form'

= link_to 'Show', [:admin, @workshop], class: 'btn btn-default'
= link_to 'Back', admin_workshops_path, class: 'btn btn-default'

app/views/admin/workshops/given.html.haml
.container
  .panel.panel-default
    .panel-heading
      =render 'workshops_heading'
      
    .panel-body
      %table.table.table-striped
        %tr
          %th 
            =Workshop.human_attribute_name(:name)
          %th 
            =Workshop.human_attribute_name(:free)
          %th 
            =Workshop.human_attribute_name(:state)
          %th 
            =Workshop.human_attribute_name(:proposed_date)
          %th
          
        - @workshops.each do |workshop|
          %tr
            %td
              = link_to workshop_path(workshop) do
                = workshop.name
            %td= workshop.free
            %td= workshop.state
            %td= workshop.proposed_date
            %td
              = link_to 'Show', [:admin, workshop], class: 'btn btn-default btn-xs'
              = link_to 'Edit', edit_admin_workshop_path(workshop), class: 'btn btn-default btn-xs'
              = link_to 'Destroy', [:admin, workshop], :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-xs'
      = paginate @workshops

app/views/admin/workshops/index.html.haml
.container
  .panel.panel-default
    .panel-heading
      =render 'workshops_heading'
  
    .panel-body
      %table.table.table-striped
        %tr
          %th 
            =Workshop.human_attribute_name(:name)
          %th 
            =Workshop.human_attribute_name(:free)
          %th 
            =Workshop.human_attribute_name(:state)
          %th 
            =Workshop.human_attribute_name(:proposed_date)
          %th
          
        - @workshops.each do |workshop|
          %tr
            %td
              = link_to workshop_path(workshop) do
                = workshop.name
            %td= workshop.free
            %td= workshop.state
            %td= workshop.proposed_date
            %td
              = link_to 'Show', [:admin, workshop], class: 'btn btn-default btn-xs'
              = link_to 'Edit', edit_admin_workshop_path(workshop), class: 'btn btn-default btn-xs'
              = link_to 'Destroy', [:admin, workshop], :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-xs'
      = paginate @workshops

app/views/admin/workshops/new.html.haml
.page-header
    %h1 New workshop

= render 'form'

= link_to 'Back', admin_workshops_path, class: 'btn btn-default'

app/views/admin/workshops/proposed.html.haml
.container
  .panel.panel-default
    .panel-heading
      =render 'workshops_heading'
      
      
    .panel-body
      %table.table.table-striped
        %tr
          %th 
            =Workshop.human_attribute_name(:name)
          %th 
            =Workshop.human_attribute_name(:free)
          %th 
            =Workshop.human_attribute_name(:state)
          %th 
            =Workshop.human_attribute_name(:proposed_date)
          %th
          
        - @workshops.each do |workshop|
          %tr
            %td
              = link_to workshop_path(workshop) do
                = workshop.name
            %td= workshop.free
            %td= workshop.state
            %td= workshop.proposed_date
            %td
              = link_to "Crear reservacion", new_admin_workshop_reservation_path(workshop) , class: 'btn btn-default btn-xs'
              = link_to 'Show', [:admin, workshop], class: 'btn btn-default btn-xs'
              = link_to 'Edit', edit_admin_workshop_path(workshop), class: 'btn btn-default btn-xs'
              = link_to 'Destroy', [:admin, workshop], :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-xs'
      = paginate @workshops

app/views/admin/workshops/scheduled.html.haml
.container
  .panel.panel-default
    .panel-heading
      =render 'workshops_heading'
      
    .panel-body
      %table.table.table-striped
        %tr
          %th 
            =Workshop.human_attribute_name(:name)
          %th 
            =Workshop.human_attribute_name(:free)
          %th 
            =Workshop.human_attribute_name(:state)
          %th
            =Venue.model_name.human
          %th 
            =Reservation.model_name.human
          %th
          
        - @workshops.each do |workshop|
          %tr
            %td
              = link_to workshop_path(workshop) do
                = workshop.name
            %td= workshop.free
            %td= workshop.state
            %td
              = link_to workshop.venue.name, workshop.venue
            %td
              = workshop.reservation.fmt_duration 
            %td
              = link_to 'Show', [:admin, workshop], class: 'btn btn-default btn-xs'
              = link_to 'Edit', edit_admin_workshop_path(workshop), class: 'btn btn-default btn-xs'
              = link_to 'Destroy', [:admin, workshop], :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-xs'
      = paginate @workshops

app/views/admin/workshops/scheduled_past.html.haml
.container
  .panel.panel-default
    .panel-heading
      =render 'workshops_heading'
      
    .panel-body
      %table.table.table-striped
        %tr
          %th 
            =Workshop.human_attribute_name(:name)
          %th 
            =Workshop.human_attribute_name(:free)
          %th 
            =Workshop.human_attribute_name(:state)
          %th
            =Venue.model_name.human
          %th 
            =Reservation.model_name.human
          %th
          
        - @workshops.each do |workshop|
          %tr
            %td
              = link_to workshop_path(workshop) do
                = workshop.name
            %td= workshop.free
            %td= workshop.state
            %td
              = link_to workshop.venue.name, workshop.venue
            %td
              = workshop.reservation.fmt_duration 
            %td
              = link_to I18n.t("views.states.given"), state_admin_workshop_path(workshop), :method => :patch, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs'
              = link_to 'Show', [:admin, workshop], class: 'btn btn-default btn-xs'
              = link_to 'Edit', edit_admin_workshop_path(workshop), class: 'btn btn-default btn-xs'
              = link_to 'Destroy', [:admin, workshop], :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-xs'
      = paginate @workshops

app/views/admin/workshops/show.html.haml
%p#notice= notice

%dl.dl-horizontal
  %dt
    %strong Name:
  %dd= @workshop.name
%dl.dl-horizontal
  %dt
    %strong Free:
  %dd= @workshop.free
%dl.dl-horizontal
  %dt
    %strong State:
  %dd= @workshop.state
%dl.dl-horizontal
  %dt
    %strong Proposed date:
  %dd= @workshop.proposed_date

= link_to 'Edit', edit_admin_workshop_path(@workshop), class: 'btn btn-default'
= link_to 'Back', admin_workshops_path, class: 'btn btn-default'