config/routes.rb
LearnyApp::Application.routes.draw do

  get 'workshops/all', as: 'all_workshops'

  namespace :admin do
    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
  
    resources :zones
    resources :reservations, only: [:edit, :destroy, :update, :show]
    resources :venues, :concerns => :paginatable do
      resources :reservations, :concerns => :paginatable, only: [:index, :show]
      resources :calendars, :concerns => :paginatable      
    end
    resources :workshops, :concerns => :paginatable do
       collection do
         get 'proposed(/page/:page)', :action => :proposed, :as => :proposed
         get 'scheduled(/page/:page)', :action => :scheduled, :as => :scheduled
         get 'scheduled/past(/page/:page)', :action => :scheduled_past, :as => :scheduled_past
         get 'given(/page/:page)', :action => :given, :as => :given
       end
       
       member do
         patch 'state'
       end
       
       resources :reservations, only: [:new, :create]
    end

    get '/' => 'administrators#index'
  
  end

  resources :contacts

  devise_for :students, :controllers => { :registrations => "students/registrations" }
  devise_for :experts, :controllers => { :registrations => "experts/registrations" }
  devise_for :venues, :controllers => { :registrations => "venues/registrations" }  
  devise_for :administrators

  get "/auth/:provider/callback" => "sessions#create"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  concern :replicable do
    get '(:id)', :action => :new, :on=> :new, :as => ''
  end

  resources :experts, only: [:show]
  resources :students, only: [:index, :show]
  resources :venues
  resources :venue_pictures
  resources :calendars
  resources :reservations
  resources :workshops, :concerns => [:paginatable, :replicable] do
    resources :student_surveys, only: [:new, :create]
  end
  resources :student_surveys, only: [:show]
  resources :enrollments, :concerns => :paginatable
  resources :guests, only: [:create]
  
  
  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/faq'      => 'high_voltage/pages#show', id: 'faq'

  get '/home', to: redirect('/')
  get 'students/index'
  get 'experts/index'
  get 'venues/index'
  
  authenticated :venue do
    root to: 'venues#index', as: :venue_root
  end

  authenticated :expert do
    root to: 'experts#index', as: :expert_root
  end

  authenticated :student do
    root to: 'students#index', as: :student_root
  end
  
  authenticated :administrator do
    root to: 'admin/administrators#index', as: :administrator_root
  end
  
  unauthenticated do
    root :to => 'high_voltage/pages#show', id: 'home'
  end

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  
  acts_as_paranoid
  obfuscate_id :spin => 13889931

  validates :title, presence: true

  has_many :reservations, dependent: :destroy
  
  belongs_to :venue

  def title  	  	
    self.title = self[:title] == "default" ? I18n.t('views.legends.calendar.main_table', default: 'Main table') : self[:title]
  end
  
  def title_with_venue
    venue.name+ ' - '+ title
  end
end

app/controllers/admin/calendars_controller.rb
class Admin::CalendarsController < ApplicationController
  before_action :set_venue, only: [:index, :new, :create]
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]


  # GET /admin/calendars
  # GET /admin/calendars.json
  def index
    @calendars = @venue.calendars.page params[:page]
  end

  # GET /admin/calendars/1
  # GET /admin/calendars/1.json
  def show
  end

  # GET /admin/calendars/new
  def new
    @calendar = @venue.calendars.build
  end

  # GET /admin/calendars/1/edit
  def edit
  end

  # POST /admin/calendars
  # POST /admin/calendars.json
  def create
    @calendar = @venue.calendars.build(calendar_params)
    respond_to do |format|
      if @calendar.save
        format.html { redirect_to [:admin,@venue, @calendar], notice: 'Calendar was successfully created.' }
        format.json { render action: 'show', status: :created, location: @calendar }
      else
        format.html { render action: 'new' }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/calendars/1
  # PATCH/PUT /admin/calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to [:admin, @venue, @calendar], notice: 'Calendar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/calendars/1
  # DELETE /admin/calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to admin_venue_calendars_path(@venue), notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:venue_id])      
    end
    
    def set_calendar
      set_venue
      @calendar = Calendar.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:title, :is_default)
    end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_venue!
  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = current_venue.calendars
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
    @calendars = current_venue.calendars
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)
    @calendar.venue=current_venue
    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_calendar
    @calendar = Calendar.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def calendar_params
    params.require(:calendar).permit(:title)
  end
end

app/helpers/admin/calendars_helper.rb
module Admin::CalendarsHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/admin/calendars/_form.html.haml
= form_for([:admin,@venue, @calendar], html: { class: 'form-horizontal  calendar'} ) do |f|
  - if @calendar.errors.any?
    #error_explanation.panel.panel-danger
      .panel-heading
        %h2.panel-title= "#{pluralize(@calendar.errors.count, "error")} prohibited this calendar from being saved:"
      .panel-body
        %ul
          - @calendar.errors.full_messages.each do |msg|
            %li= msg

  .form-group
    = f.label :title, class: 'control-label col-md-2'
    .col-md-10= f.text_field :title, class: 'form-control'
    .col-md-offset-2.col-md-10
      = f.label :is_default, for: nil do
        = f.check_box :is_default
        = Calendar.human_attribute_name(:is_default)
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, class: 'btn btn-primary'

app/views/admin/calendars/edit.html.haml
.container
  .panel.panel-default
    .panel-heading
      %h5 Editing calendar
    .panel-body
      = render 'form'
      
      = link_to 'Show', [:admin,@venue, @calendar], class: 'btn btn-default'
      = link_to 'Back', admin_venue_calendars_path(@venue), class: 'btn btn-default'

app/views/admin/calendars/index.html.haml
.container
  .panel.panel-default
    .panel-heading
      %h4 #{@venue.name} - #{Calendar.model_name.human.pluralize}
    .panel-body 
      %table.table.table-striped
        %tr
          %th 
            = Calendar.human_attribute_name(:title)
          %th 
            = Calendar.human_attribute_name(:is_default)
          %th
            = Calendar.human_attribute_name(:created_at)
          %th
            = Calendar.human_attribute_name(:updated_at)
          %th
      
        - @calendars.each do |calendar|
          %tr
            %td= calendar.title
            %td= calendar.is_default
            %td= calendar.created_at
            %td= calendar.updated_at
            %td
              = link_to 'Show', [:admin, @venue,calendar], class: 'btn btn-default btn-xs'
              = link_to 'Edit', edit_admin_venue_calendar_path(@venue,calendar), class: 'btn btn-default btn-xs'
              = link_to 'Destroy', [:admin,@venue, calendar], :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-xs'
      
      = paginate @calendars        
      %br
      = link_to 'New Calendar', new_admin_venue_calendar_path(@venue), class: 'btn btn-primary'
      = link_to Venue.model_name.human.pluralize, admin_venues_path, class: 'btn btn-default'
      
      %br

app/views/admin/calendars/new.html.haml
.container
  .panel.panel-default
    .panel-heading
      %h1 New calendar
    .panel-body
      = render 'form'
      
      = link_to 'Back', admin_venue_calendars_path(@venue), class: 'btn btn-default'

app/views/admin/calendars/show.html.haml
.container
  %dl.dl-horizontal
    %dt
      %strong 
        =Calendar.human_attribute_name(:title)
    %dd= @calendar.title
  %dl.dl-horizontal
    %dt
      %strong 
        =Calendar.human_attribute_name(:is_default)
    %dd= @calendar.is_default
  %dl.dl-horizontal
    %dt
      =Calendar.human_attribute_name(:created_at)
    %dd= @calendar.created_at
  %dl.dl-horizontal
    %dt
      %strong
        =Calendar.human_attribute_name(:updated_at)
    %dd= @calendar.updated_at
  
  
  
  = link_to 'Edit', edit_admin_venue_calendar_path(@venue,@calendar), class: 'btn btn-default'
  = link_to 'Back', admin_venue_calendars_path(@venue), class: 'btn btn-default'