config/routes.rb
LearnyApp::Application.routes.draw do

  get 'workshops/all', as: 'all_workshops'

  namespace :admin do
    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection, :as => ''
    end
  
    resources :zones
    resources :reservations, only: [:edit, :destroy, :update, :show]
    resources :venues, :concerns => :paginatable do
      resources :reservations, :concerns => :paginatable, only: [:index, :show]
      resources :calendars, :concerns => :paginatable      
    end
    resources :workshops, :concerns => :paginatable do
       collection do
         get 'proposed(/page/:page)', :action => :proposed, :as => :proposed
         get 'scheduled(/page/:page)', :action => :scheduled, :as => :scheduled
         get 'scheduled/past(/page/:page)', :action => :scheduled_past, :as => :scheduled_past
         get 'given(/page/:page)', :action => :given, :as => :given
       end
       
       member do
         patch 'state'
       end
       
       resources :reservations, only: [:new, :create]
    end

    get '/' => 'administrators#index'
  
  end

  resources :contacts

  devise_for :students, :controllers => { :registrations => "students/registrations" }
  devise_for :experts, :controllers => { :registrations => "experts/registrations" }
  devise_for :venues, :controllers => { :registrations => "venues/registrations" }  
  devise_for :administrators

  get "/auth/:provider/callback" => "sessions#create"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  concern :replicable do
    get '(:id)', :action => :new, :on=> :new, :as => ''
  end

  resources :experts, only: [:show]
  resources :students, only: [:index, :show]
  resources :venues
  resources :venue_pictures
  resources :calendars
  resources :reservations
  resources :workshops, :concerns => [:paginatable, :replicable] do
    resources :student_surveys, only: [:new, :create]
  end
  resources :student_surveys, only: [:show]
  resources :enrollments, :concerns => :paginatable
  resources :guests, only: [:create]
  
  
  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/faq'      => 'high_voltage/pages#show', id: 'faq'

  get '/home', to: redirect('/')
  get 'students/index'
  get 'experts/index'
  get 'venues/index'
  
  authenticated :venue do
    root to: 'venues#index', as: :venue_root
  end

  authenticated :expert do
    root to: 'experts#index', as: :expert_root
  end

  authenticated :student do
    root to: 'students#index', as: :student_root
  end
  
  authenticated :administrator do
    root to: 'admin/administrators#index', as: :administrator_root
  end
  
  unauthenticated do
    root :to => 'high_voltage/pages#show', id: 'home'
  end

end

app/models/student_survey.rb
class StudentSurvey < ActiveRecord::Base
  validates :rating_workshop, :rating_venue, :rating_expert, :rating_learny, :workshop, :student, presence: true
  belongs_to :workshop
  belongs_to :student
  
  validates :rating_workshop,:rating_venue, :rating_expert, :rating_learny, 
    numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5, only_integer: true }, allow_nil: true
  
  
  #1 encuesta por estudiante por taller
  #estado de taller en given
  #estudiante inscrito en taller
  #ratings de 0 a 5
  #longitud maxima de comentario en 1000
  
  validate :workshop_has_not_been_given, :student_not_enrolled
  validate :survey_already_done, on: :create
  
  
  private
  
  def workshop_has_not_been_given
    unless workshop.given?
      message=I18n.t('activerecord.errors.models.student_survey.attributes.workshop.not_given')
        #puts ">>> workshop_reserved? #{count} #{message}" 
      errors.add(:workshop_id, message)
    end
  end
  
  def student_not_enrolled
    unless workshop.student_enrolled? student
      message=I18n.t('activerecord.errors.models.student_survey.attributes.workshop.student_not_enrolled')
        #puts ">>> workshop_reserved? #{count} #{message}" 
      errors.add(:workshop_id, message)
    end
  end
  
  def survey_already_done
    if workshop.student_survey_done? student
      message=I18n.t('activerecord.errors.models.student_survey.attributes.workshop.survey_already_done')
        #puts ">>> workshop_reserved? #{count} #{message}" 
      errors.add(:workshop_id, message)
    end
  end
end

app/controllers/student_surveys_controller.rb
class StudentSurveysController < ApplicationController
  
  before_action :set_workshop, only: [:new, :create]
  before_action :set_student_survey, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_student!

  # GET /student_surveys
  # GET /student_surveys.json
  def index
    @student_surveys = StudentSurvey.all
  end

  # GET /student_surveys/1
  # GET /student_surveys/1.json
  def show
  end

  # GET /student_surveys/new
  def new
    @student_survey = StudentSurvey.new(workshop: @workshop, student: current_student)
    unless @student_survey.valid?
      #flash[:error]=@student_survey.errors.full_messages
      redirect_to student_root_path, alert: @student_survey.errors.full_messages.first
    end
  end

  # GET /student_surveys/1/edit
  def edit
  end

  # POST /student_surveys
  # POST /student_surveys.json
  def create
    @student_survey = StudentSurvey.new(
      student_survey_params.merge({workshop: @workshop, student: current_student}))

    respond_to do |format|
      if @student_survey.save
        format.html { redirect_to @student_survey, notice: I18n.t('controllers.students_survey.create',default: 'Student survey was successfully created.') }
        format.json { render :show, status: :created, location: @student_survey }
      else
        format.html { render :new }
        format.json { render json: @student_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_surveys/1
  # PATCH/PUT /student_surveys/1.json
  def update
    respond_to do |format|
      if @student_survey.update(student_survey_params)
        format.html { redirect_to @student_survey, notice: 'Student survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_survey }
      else
        format.html { render :edit }
        format.json { render json: @student_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_surveys/1
  # DELETE /student_surveys/1.json
  def destroy
    @student_survey.destroy
    respond_to do |format|
      format.html { redirect_to student_surveys_url, notice: 'Student survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_survey
      @student_survey = StudentSurvey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_survey_params
      params.require(:student_survey).permit(:rating_workshop, :rating_expert, 
        :rating_venue, :rating_learny, :workshop_comment, :venue_comment)
    end
    
    def set_workshop
      @workshop = Workshop.find(params[:workshop_id])
    end
end

app/helpers/student_surveys_helper.rb
module StudentSurveysHelper
end

app/views/student_surveys/_form.html.haml
= form_for [@workshop,@student_survey], html: {class: "center",role:'form'} do |f|
  - if @student_survey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@student_survey.errors.count, "error")} prohibited this student_survey from being saved:"
      %ul
        - @student_survey.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col.col-md-6
      .form-group
        = f.label :rating_workshop
        = f.text_field :rating_workshop,  class: 'form-control rating', 'data-step'=> '1.0' , 'data-show-caption' =>'false'
      .form-group
        = f.label :rating_expert
        = f.text_field :rating_expert,  :class => 'form-control rating', 'data-step'=> '1.0' , 'data-show-caption' =>'false'
      .form-group
        = f.label :rating_venue
        = f.text_field :rating_venue,  :class => 'form-control rating', 'data-step'=> '1.0' , 'data-show-caption' =>'false'
      .form-group
        = f.label :rating_learny
        = f.text_field :rating_learny,  :class => 'form-control rating', 'data-step'=> '1.0' , 'data-show-caption' =>'false'
    .col.col-md-6
      .form-group
        = f.label :workshop_comment
        = f.text_area :workshop_comment, :class => 'form-control', :rows=>3
      .form-group
        = f.label :venue_comment
        = f.text_area :venue_comment, :class => 'form-control', :rows=>3

      .actions
        = f.submit 'Save', :class => 'btn btn-primary btn-lg btn-block'
    

app/views/student_surveys/edit.html.haml
%h1 Editing student_survey

= render 'form'

= link_to 'Show', @student_survey
\|
= link_to 'Back', student_surveys_path

app/views/student_surveys/index.html.haml
%h1 Listing student_surveys

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @student_surveys.each do |student_survey|
      %tr
        %td= link_to 'Show', student_survey
        %td= link_to 'Edit', edit_student_survey_path(student_survey)
        %td= link_to 'Destroy', student_survey, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Student survey', new_student_survey_path

app/views/student_surveys/new.html.haml
.container
  %h3 #{StudentSurvey.model_name.human} para #{@workshop.name}
  
  = render 'form'

app/views/student_surveys/show.html.haml
.container
  
  = link_to 'Back', student_root_path, class: 'btn btn-default btn-lg'